const $=id=>document.getElementById(id);
const demo=new URLSearchParams(location.search).get('demo')==='1';
let sb,report,token,demoDrafts=[];
const usd=n=>n===null||n===undefined?'Unknown':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:Math.abs(n)<.01?5:2}).format(n);
const today=new Date();$('from').value=new Date(Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),1)).toISOString().slice(0,10);$('to').value=new Date(Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),today.getUTCDate()+1)).toISOString().slice(0,10);
function toast(message){$('toast').textContent=message;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',6000);}
function row(target,values){const tr=document.createElement('tr');for(const value of values){const td=document.createElement('td');td.textContent=value;tr.append(td);}$(target).append(tr);}
function table(target,rows,empty){$(target).replaceChildren();if(!rows.length)row(target,[empty]);else rows.forEach(values=>row(target,values));}
async function request(body){
 if(demo){if(body?.action==='price_draft')demoDrafts.unshift({draft_id:body.submissionId,products:body.products,free_credits:body.freeCredits,status:'draft',created_at:new Date().toISOString()});return{saved:true,message:'Demo only: edit simulated; no financial record changed.'};}
 const {data}=await sb.auth.getSession();token=data.session?.access_token;
 if(!token)throw new Error('Sign in to your Prism owner account, then reopen this page.');
 const url='/api/owner-finance'+(body?'':`?from=${$('from').value}&to=${$('to').value}`);
 const r=await fetch(url,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const dataOut=await r.json();if(!r.ok)throw new Error(dataOut.error||'Report unavailable');return dataOut;
}
function sample(){const d=$('from').value;return{mode:'demo',generatedAt:new Date().toISOString(),captureStartedAt:new Date().toISOString(),dailyAlertUsd:1,totals:{cashReceivedUsd:29.97,refundsUsd:0,knownAiCostUsd:.0528,allocatedRevenueUsd:3.5964,operatingProfitUsd:null,netProfitUsd:null,recordedCostProfitEstimateUsd:-2.3264,initialQueries:12,followUpQueries:18,completedQueries:30,unclassifiedQueries:0,recordedExpensesUsd:4.10,recordedFeesUsd:1.77,knownCashResultUsd:24.0472,totalCredits:42,freeCredits:6,bankCredits:36,paidLotCredits:36,pendingPaidCredits:264,failedAttempts:1,unknownAttempts:1,missingCapture:0,unlinkedAttempts:1,testCashUsd:0,unmatchedBankCredits:0},alerts:[{severity:'warning',message:'Sample figures only. This demo is not connected to production.'},{severity:'warning',message:'One provider attempt has an unknown charge.'},{severity:'warning',message:'Hosting and database statement coverage require reconciliation.'}],configuredProducts:{subscription:{monthlyPriceCents:4999,monthlyCredits:350},queryBanks:{1999:125},explorer:{credits:5,windowHours:24}},priceDrafts:demoDrafts,conversations:[{threadId:'sample-long-conversation',stages:19,credits:8,knownCostUsd:.027,unknownAttempts:0},{threadId:'sample-short-conversation',stages:5,credits:3,knownCostUsd:.00217,unknownAttempts:0},{threadId:null,requestId:'sample-failed-request',stages:1,credits:0,knownCostUsd:.0005,unknownAttempts:1}],daily:[{date:d,knownCostUsd:.015,unknownAttempts:0},{date:d.slice(0,8)+'02',knownCostUsd:.0378,unknownAttempts:1}],usage:[],expenses:[{category:'database',reference:'Sample invoice',amount_usd:4.10}],disclosure:'DEMO: all figures are illustrative. No live financial data or real owner access is provided by demo mode.'};}
function render(r){report=r;const t=r.totals;$('environment').textContent=demo?'DEMO · SAMPLE DATA':r.mode.toUpperCase()+' · OWNER';$('access').textContent=demo?'Demo only. Sample financial figures and simulated edits. Real records require a verified owner account.':r.mode==='preview'?'Isolated preview: test activity. These are not your production business finances.':'Owner report. Missing records remain explicit.';$('app').hidden=false;$('cash').textContent=usd(t.cashReceivedUsd);$('ai').textContent=usd(t.knownAiCostUsd);$('earned').textContent=usd(t.allocatedRevenueUsd);$('profit').textContent=t.netProfitUsd==null?'Not reconciled':usd(t.netProfitUsd);$('profit-note').textContent=t.netProfitUsd==null?`Recorded-cost estimate: ${usd(t.recordedCostProfitEstimateUsd)} · incomplete`:'FIFO-estimated earned revenue less recorded costs · before tax';$('initial-queries').textContent=t.initialQueries;$('follow-up-queries').textContent=t.followUpQueries;$('query-count-note').textContent=`${t.completedQueries} completed queries in this period · ${t.totalCredits} credits consumed${t.unclassifiedQueries?` · ${t.unclassifiedQueries} unclassified`:''}. Counts include free usage and exclude failed attempts and internal AI stages.`;$('updated').textContent='Updated '+new Date(r.generatedAt).toLocaleString()+'. Capture begins '+(r.captureStartedAt?new Date(r.captureStartedAt).toLocaleString():'when enabled')+'.';$('ai-note').textContent=`${t.unknownAttempts} unknown/pending charges · usage-derived`;
 $('alerts').replaceChildren();for(const a of r.alerts){const li=document.createElement('li');li.textContent=a.message;li.className=a.severity;$('alerts').append(li);}if(!r.alerts.length){const li=document.createElement('li');li.textContent='No configured alerts for this period.';$('alerts').append(li);}
 $('stats').replaceChildren();for(const [label,value] of [['Credits consumed',t.totalCredits],['Explorer/trial credits',t.freeCredits],['Bank credits (may include gifts)',t.bankCredits],['Failed AI attempts',t.failedAttempts],['Pending paid credits',t.pendingPaidCredits],['Uncaptured completions',t.missingCapture],['Recorded fees',usd(t.recordedFeesUsd)],['Recorded expenses',usd(t.recordedExpensesUsd)]]){const el=document.createElement('span');el.textContent=label+': ';const strong=document.createElement('strong');strong.textContent=value;el.append(strong);$('stats').append(el);}
 $('chart').replaceChildren();const max=Math.max(.000001,...r.daily.map(d=>d.knownCostUsd));for(const d of r.daily.slice(-31)){const group=document.createElement('div');group.className='bar-group';const val=document.createElement('span');val.textContent=usd(d.knownCostUsd);const bar=document.createElement('div');bar.className='bar';bar.style.height=(d.knownCostUsd/max*90)+'px';bar.title=d.date+': '+usd(d.knownCostUsd);const date=document.createElement('span');date.textContent=d.date.slice(5);group.append(val,bar,date);$('chart').append(group);}if(!r.daily.length)$('chart').textContent='No captured AI attempts in this reporting period.';$('alert').value=r.dailyAlertUsd;
 table('conversations',r.conversations.map(c=>[c.threadId||'Unlinked '+c.requestId,c.stages,c.credits,usd(c.knownCostUsd),c.unknownAttempts]),'No conversations in this period.');table('usage',r.usage.map(u=>[new Date(u.created_at).toLocaleString(),u.stage,u.model,u.state,usd(u.cost_usd)]),'No provider attempts recorded.');table('expense-rows',r.expenses.map(e=>[e.category,e.reference,usd(e.amount_usd)]),'No expenses recorded; this does not mean expenses were zero.');
 const p=r.configuredProducts;const bank=Object.entries(p.queryBanks)[0];$('configured').textContent=`Published configuration: membership ${usd(p.subscription.monthlyPriceCents/100)} / ${p.subscription.monthlyCredits} credits; bank ${usd(Number(bank[0])/100)} / ${bank[1]} credits; ${p.explorer.credits} free credits per ${p.explorer.windowHours} hours. Drafts do not affect these values.`;
 const draft=r.priceDrafts[0];const sub=draft?.products.find(p=>p.key==='subscription');const b=draft?.products.find(p=>p.key==='bank');$('membership-price').value=(sub?.priceCents??p.subscription.monthlyPriceCents)/100;$('membership-credits').value=sub?.credits??p.subscription.monthlyCredits;$('bank-price').value=(b?.priceCents??Number(bank[0]))/100;$('bank-credits').value=b?.credits??bank[1];$('free-credits').value=draft?.free_credits??p.explorer.credits;priceMath();$('draft-history').replaceChildren();for(const d of r.priceDrafts){const el=document.createElement('p');el.textContent=new Date(d.created_at).toLocaleString()+' · DRAFT · '+d.products.map(p=>`${p.key}: ${usd(p.priceCents/100)} / ${p.credits} credits`).join(' · ')+` · Free: ${d.free_credits}`;$('draft-history').append(el);}if(!r.priceDrafts.length)$('draft-history').textContent='No saved drafts.';$('disclosure').textContent=r.disclosure;
}
function priceMath(){for(const prefix of ['membership','bank']){const price=Number($(prefix+'-price').value),credits=Number($(prefix+'-credits').value),unit=price/credits;$(prefix+'-unit').textContent=credits>0?`$${unit.toFixed(4)} per credit · initial $${(unit*2).toFixed(4)} · follow-up $${unit.toFixed(4)}`:'Enter a positive credit allocation.';}}
async function load(){try{render(demo?sample():await request());}catch(e){$('app').hidden=true;$('access').textContent=e.message+' ';const a=document.createElement('a');a.href='/qt-gateway.html';a.textContent='Open Prism sign-in';$('access').append(a);}}
async function save(form,body){const button=form.querySelector('button');button.disabled=true;try{const r=await request(body);toast(r.message||'Saved.');await load();}catch(e){toast(e.message);}finally{button.disabled=false;}}
$('range').addEventListener('submit',e=>{e.preventDefault();load();});$('price-form').addEventListener('input',priceMath);$('price-form').addEventListener('submit',e=>{e.preventDefault();save(e.target,{action:'price_draft',submissionId:crypto.randomUUID(),products:[{key:'subscription',priceCents:Math.round(Number($('membership-price').value)*100),credits:Number($('membership-credits').value)},{key:'bank',priceCents:Math.round(Number($('bank-price').value)*100),credits:Number($('bank-credits').value)}],freeCredits:Number($('free-credits').value)});});
$('expense-form').addEventListener('submit',e=>{e.preventDefault();save(e.target,{action:'expense',submissionId:crypto.randomUUID(),category:$('expense-category').value,amountCents:Math.round(Number($('expense-amount').value)*100),reference:$('expense-reference').value,from:$('from').value,to:$('to').value});});$('coverage-form').addEventListener('submit',e=>{e.preventDefault();save(e.target,{action:'coverage',submissionId:crypto.randomUUID(),category:$('coverage-category').value,amountCents:0,reference:$('coverage-reference').value,from:$('from').value,to:$('to').value});});$('alert-form').addEventListener('submit',e=>{e.preventDefault();save(e.target,{action:'alert',dailyAlertUsd:Number($('alert').value)});});
$('download').addEventListener('click',()=>{if(!report)return;const columns=['attempt_id','created_at','stage','model','state','input_tokens','output_tokens','cost_usd','cost_status'];const csv=[columns.join(','),...report.usage.map(r=>columns.map(k=>'"'+String(r[k]??'').replace(/^[=+\-@]/,"'").replaceAll('"','""')+'"').join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='prism-usage-'+$('from').value+'.csv';a.click();URL.revokeObjectURL(a.href);toast('Export contains the latest 100 attempts in this report.');});
if(!demo){const config=window.PRISM_PUBLIC_CONFIG;if(config?.supabaseUrl&&config?.supabaseAnonKey&&window.supabase)sb=window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey);else{$('access').textContent='Public authentication configuration is unavailable.';}}
if(demo||sb)load();
