// api/followups.js
// Save and retrieve follow-up queries for a thread — the main Q&A chain
// (R1, R2, R3...), billed, generated by real /api/interpret calls.
//
// ALSO handles Refractions private notes ("My Thoughts") — merged into this
// same file/function rather than a separate api/refractions.js, specifically
// to stay within Vercel Hobby's 12-Serverless-Function limit. Requests for
// notes are distinguished by a ?kind=note query param and routed to
// handleNoteRequest() below; everything else falls through to the original
// follow-up logic. Same behavior either way, just one fewer file deployed.
//
// Contexts the follow-up logic handles:
//   1. Owner (x-user-email) — full access to their own thread
//   2. Share page (x-share-id) — anonymous read/write on a shared thread,
//      unrelated to Trust Circle — this is the original, free, no-account
//      commentary feature and is untouched by anything below
//   3. Trust Circle participant (x-user-email) — an authenticated person who
//      has joined a Trust Circle thread via thread_participants, adding a
//      genuine new interpretive follow-up billed to their own account,
//      exactly as they would in their own thread — no different UI, no
//      different cost, just the same main-view follow-up flow
//
// Visibility note: unlike Refractions notes (refraction_notes), the main
// Q&A chain has NO per-entry private/public split. Once a thread is Trust
// Circle, every follow-up in it is visible to the whole circle by default —
// hiding an actual interpretive answer was confirmed out of scope for this
// table.
//
// Deletion: only the author of a follow-up can ever delete it. Not the
// thread owner, not any other participant, no exceptions.
//
// Muting: purely personal, scoped to (thread, muter, muted). Filtering here
// only ever affects what the MUTER sees — never removes anything for anyone
// else, never notifies the muted person.

const SUPABASE_URL              = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

function sbHeaders(extra) {
  return {
    'apikey':        SUPABASE_SERVICE_ROLE_KEY,
    'Authorization': `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
    ...extra
  };
}

async function getSubscriberId(userEmail) {
  const res = await fetch(
    `${SUPABASE_URL}/rest/v1/subscribers?email=eq.${encodeURIComponent(userEmail)}&select=id&limit=1`,
    { headers: sbHeaders() }
  );
  const subs = await res.json();
  return subs?.[0]?.id || null;
}

async function getMutedUserIds(threadId, viewerUserId) {
  if (!viewerUserId) return [];
  const res = await fetch(
    `${SUPABASE_URL}/rest/v1/thread_mutes?thread_id=eq.${threadId}&muter_user_id=eq.${viewerUserId}&select=muted_user_id`,
    { headers: sbHeaders() }
  );
  const rows = await res.json();
  return Array.isArray(rows) ? rows.map(r => r.muted_user_id) : [];
}

// Applies the one viewer-specific filter that applies to the main Q&A
// chain: hide anything from someone this viewer has muted in this thread.
// No per-entry private/public split here — see the file header note.
function filterForViewer(followUps, mutedIds) {
  return followUps.filter(f => !(f.user_id && mutedIds.includes(f.user_id)));
}

// ── Refractions private notes ──────────────────────────────────────────────
// Now backed by its own dedicated table, refraction_notes — no longer
// sharing share_chat_messages with the anonymous social layer at all. That
// was the seam that caused real bugs earlier (the share_id NOT NULL issue);
// a private note has nothing to do with sharing and now lives somewhere
// that reflects that. Still merged into this file rather than its own
// api/refractions.js, purely to stay within Vercel Hobby's 12-function cap.
//
// Author-scoped throughout: a note is only ever visible, editable, or
// deletable by whoever wrote it. quote is optional — a note can exist with
// or without a highlighted passage attached.
async function handleNoteRequest(req, res) {
  const userEmail = req.headers['x-user-email']   || null;
  const anonId    = req.headers['x-anon-session'] || null;
  if (!userEmail && !anonId) return res.status(401).json({ error: 'Unauthorized' });

  // Resolve to exactly one owner identity — a real account if signed in,
  // otherwise the anonymous session identifier. A note anchored to an
  // anon session today is exactly what the migration step (still to come)
  // will hand over to a real user_id once that session registers.
  let userId = null;
  if (userEmail) {
    userId = await getSubscriberId(userEmail);
    if (!userId) return res.status(404).json({ error: 'Subscriber not found' });
  }

  // Query-string fragment and insert fields, built once, used everywhere
  // below — keeps every branch correct for both identity types without
  // duplicating the same if/else four times.
  const ownerFilter = userId
    ? `user_id=eq.${userId}`
    : `anon_session_id=eq.${encodeURIComponent(anonId)}`;
  const ownerFields = userId
    ? { user_id: userId, anon_session_id: null }
    : { user_id: null, anon_session_id: anonId };

  if (req.method === 'GET') {
    const threadId = req.query?.threadId || null;
    const nodeId    = req.query?.nodeId  || 'root';
    if (!threadId) return res.status(400).json({ error: 'threadId required' });

    const notesRes = await fetch(
      `${SUPABASE_URL}/rest/v1/refraction_notes?thread_id=eq.${encodeURIComponent(threadId)}&node_id=eq.${encodeURIComponent(nodeId)}&${ownerFilter}&order=created_at.asc&select=id,quote,title,content,created_at,edited_at`,
      { headers: sbHeaders() }
    );
    const notes = await notesRes.json();
    return res.status(200).json({ notes: Array.isArray(notes) ? notes : [] });
  }

  if (req.method === 'POST') {
    let body;
    try {
      body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    } catch {
      return res.status(400).json({ error: 'Invalid JSON' });
    }
    const { threadId, nodeId, content, quote, title } = body || {};
    if (!threadId) return res.status(400).json({ error: 'threadId required' });
    if (!quote && !title) return res.status(400).json({ error: 'quote or title required' });

    const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/refraction_notes`, {
      method: 'POST',
      headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'return=representation' }),
      body: JSON.stringify({
        thread_id: threadId,
        node_id:   nodeId || 'root',
        quote:     quote || null,
        title:     title || null,
        content:   content || '',
        ...ownerFields
      })
    });

    if (!insertRes.ok) {
      const err = await insertRes.text();
      console.error('note insert failed:', err);
      return res.status(500).json({ error: 'Failed to save note' });
    }

    const saved = await insertRes.json();
    return res.status(200).json({ success: true, note: saved?.[0] || null });
  }

  if (req.method === 'PATCH') {
    let body;
    try {
      body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    } catch {
      return res.status(400).json({ error: 'Invalid JSON' });
    }
    const { noteId, content, title } = body || {};
    if (!noteId) return res.status(400).json({ error: 'noteId required' });
    if (content === undefined && title === undefined) {
      return res.status(400).json({ error: 'content or title required' });
    }

    const ownRes = await fetch(
      `${SUPABASE_URL}/rest/v1/refraction_notes?id=eq.${noteId}&${ownerFilter}&select=id&limit=1`,
      { headers: sbHeaders() }
    );
    const ownRows = await ownRes.json();
    if (!ownRows?.length) return res.status(403).json({ error: 'Only the author can edit this note' });

    const updates = { edited_at: new Date().toISOString() };
    if (content !== undefined) updates.content = content;
    if (title !== undefined) updates.title = title;

    await fetch(
      `${SUPABASE_URL}/rest/v1/refraction_notes?id=eq.${noteId}`,
      {
        method: 'PATCH',
        headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'return=minimal' }),
        body: JSON.stringify(updates)
      }
    );
    return res.status(200).json({ success: true });
  }

  if (req.method === 'DELETE') {
    const { noteId } = req.body || {};
    if (!noteId) return res.status(400).json({ error: 'noteId required' });

    const ownRes = await fetch(
      `${SUPABASE_URL}/rest/v1/refraction_notes?id=eq.${noteId}&${ownerFilter}&select=id&limit=1`,
      { headers: sbHeaders() }
    );
    const ownRows = await ownRes.json();
    if (!ownRows?.length) return res.status(403).json({ error: 'Only the author can delete this note' });

    await fetch(
      `${SUPABASE_URL}/rest/v1/refraction_notes?id=eq.${noteId}`,
      { method: 'DELETE', headers: sbHeaders() }
    );
    return res.status(200).json({ success: true });
  }

  return res.status(405).json({ error: 'Method not allowed' });
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PATCH, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, x-user-email, x-share-id');
  if (req.method === 'OPTIONS') return res.status(200).end();

  // Route to the notes branch before anything else — completely separate
  // logic, sharing only the file (and the sbHeaders/getSubscriberId helpers)
  // to stay within the serverless function count limit.
  if (req.query?.kind === 'note') {
    return handleNoteRequest(req, res);
  }

  const userEmail = req.headers['x-user-email'] || null;
  const shareId   = req.headers['x-share-id']   || null;

  // ── GET — fetch follow-ups for a thread ──────────────────────────────────
  if (req.method === 'GET') {
    const threadId = req.query?.threadId || null;
    if (!threadId) return res.status(400).json({ error: 'threadId required' });

    // Share page context — untouched, separate from Trust Circle entirely.
    if (shareId) {
      const shareRes = await fetch(
        `${SUPABASE_URL}/rest/v1/shares?id=eq.${encodeURIComponent(shareId)}&thread_id=eq.${encodeURIComponent(threadId)}&select=id&limit=1`,
        { headers: sbHeaders() }
      );
      const shares = await shareRes.json();
      if (shares?.length) {
        const fuRes = await fetch(
          `${SUPABASE_URL}/rest/v1/follow_ups?thread_id=eq.${encodeURIComponent(threadId)}&order=created_at.asc&select=id,query,response,source,created_at,share_id,user_id`,
          { headers: sbHeaders() }
        );
        const followUps = await fuRes.json();
        return res.status(200).json({ followUps: Array.isArray(followUps) ? followUps : [] });
      }
    }

    if (!userEmail) return res.status(401).json({ error: 'Unauthorized' });

    const viewerUserId = await getSubscriberId(userEmail);
    if (!viewerUserId) return res.status(404).json({ error: 'Subscriber not found' });

    const [threadRes, participantRes] = await Promise.all([
      fetch(`${SUPABASE_URL}/rest/v1/threads?id=eq.${threadId}&select=id,user_id&limit=1`, { headers: sbHeaders() }),
      fetch(`${SUPABASE_URL}/rest/v1/thread_participants?thread_id=eq.${threadId}&user_id=eq.${viewerUserId}&select=id&limit=1`, { headers: sbHeaders() })
    ]);
    const threadRows = await threadRes.json();
    const participantRows = await participantRes.json();
    const isOwner = threadRows?.[0]?.user_id === viewerUserId;
    const isParticipant = Array.isArray(participantRows) && participantRows.length > 0;

    if (!isOwner && !isParticipant) {
      return res.status(403).json({ error: 'Not authorized to view this thread' });
    }

    const fuRes = await fetch(
      `${SUPABASE_URL}/rest/v1/follow_ups?thread_id=eq.${encodeURIComponent(threadId)}&order=created_at.asc&select=id,query,response,source,created_at,share_id,user_id`,
      { headers: sbHeaders() }
    );
    const followUps = await fuRes.json();
    const mutedIds = await getMutedUserIds(threadId, viewerUserId);
    const visible = filterForViewer(Array.isArray(followUps) ? followUps : [], mutedIds);

    return res.status(200).json({ followUps: visible });
  }

  // ── POST — save a follow-up ───────────────────────────────────────────────
  if (req.method === 'POST') {
    let body;
    try {
      body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    } catch {
      return res.status(400).json({ error: 'Invalid JSON' });
    }

    const { threadId, question, response, source, shareId: bodyShareId } = body || {};
    if (!threadId || !question) return res.status(400).json({ error: 'threadId and question required' });

    const postSource  = source || 'owner';
    const postShareId = bodyShareId || shareId || null;

    if (postSource === 'recipient' && postShareId) {
      const shareRes = await fetch(
        `${SUPABASE_URL}/rest/v1/shares?id=eq.${encodeURIComponent(postShareId)}&thread_id=eq.${encodeURIComponent(threadId)}&status=eq.active&select=id&limit=1`,
        { headers: sbHeaders() }
      );
      const shares = await shareRes.json();
      if (!shares?.length) {
        return res.status(403).json({ error: 'Share not found, inactive, or does not match thread' });
      }

      const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/follow_ups`, {
        method: 'POST',
        headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'return=representation' }),
        body: JSON.stringify({
          thread_id:    threadId,
          user_id:      null,
          query:        question,
          response:     typeof response === 'string' ? { text: response } : (response || {}),
          query_cost:   0,
          submitted_in: 'share',
          source:       'recipient',
          share_id:     postShareId
        })
      });

      if (!insertRes.ok) {
        const err = await insertRes.text();
        console.error('recipient follow-up insert failed:', err);
        return res.status(500).json({ error: 'Failed to save follow-up' });
      }

      const saved = await insertRes.json();
      return res.status(200).json({ success: true, id: saved?.[0]?.id });
    }

    if (postSource === 'participant') {
      if (!userEmail) return res.status(401).json({ error: 'Unauthorized' });
      const participantUserId = await getSubscriberId(userEmail);
      if (!participantUserId) return res.status(404).json({ error: 'Subscriber not found' });

      const partRes = await fetch(
        `${SUPABASE_URL}/rest/v1/thread_participants?thread_id=eq.${threadId}&user_id=eq.${participantUserId}&active=eq.true&select=id&limit=1`,
        { headers: sbHeaders() }
      );
      const partRows = await partRes.json();
      if (!partRows?.length) {
        return res.status(403).json({ error: 'Must be an active participant on this thread to contribute' });
      }

      const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/follow_ups`, {
        method: 'POST',
        headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'return=representation' }),
        body: JSON.stringify({
          thread_id:    threadId,
          user_id:      participantUserId,
          query:        question,
          response:     typeof response === 'string' ? { text: response } : (response || {}),
          query_cost:   1,
          submitted_in: 'participant',
          source:       'participant',
          share_id:     null
        })
      });

      if (!insertRes.ok) {
        const err = await insertRes.text();
        console.error('participant follow-up insert failed:', err);
        return res.status(500).json({ error: 'Failed to save follow-up' });
      }

      await fetch(
        `${SUPABASE_URL}/rest/v1/thread_participants?thread_id=eq.${threadId}&user_id=eq.${participantUserId}`,
        {
          method: 'PATCH',
          headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'return=minimal' }),
          body: JSON.stringify({ last_seen_at: new Date().toISOString() })
        }
      );

      const saved = await insertRes.json();
      return res.status(200).json({ success: true, id: saved?.[0]?.id });
    }

    if (!userEmail) return res.status(401).json({ error: 'Unauthorized' });

    const ownerUserId = await getSubscriberId(userEmail);
    if (!ownerUserId) return res.status(404).json({ error: 'Subscriber not found' });

    const threadRes = await fetch(
      `${SUPABASE_URL}/rest/v1/threads?id=eq.${threadId}&user_id=eq.${ownerUserId}&select=id&limit=1`,
      { headers: sbHeaders() }
    );
    const threads = await threadRes.json();
    if (!threads?.length) return res.status(403).json({ error: 'Thread not found or not owned by user' });

    const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/follow_ups`, {
      method: 'POST',
      headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'return=representation' }),
      body: JSON.stringify({
        thread_id:    threadId,
        user_id:      ownerUserId,
        query:        question,
        response:     typeof response === 'string' ? { text: response } : (response || {}),
        query_cost:   1,
        submitted_in: 'solo',
        source:       'owner',
        share_id:     null
      })
    });

    if (!insertRes.ok) {
      const err = await insertRes.text();
      console.error('owner follow-up insert failed:', err);
      return res.status(500).json({ error: 'Failed to save follow-up' });
    }

    const saved = await insertRes.json();
    return res.status(200).json({ success: true, id: saved?.[0]?.id });
  }

  // ── DELETE — remove my own contribution ──────────────────────────────────
  if (req.method === 'DELETE') {
    if (!userEmail) return res.status(401).json({ error: 'Unauthorized' });
    const { followUpId } = req.body || {};
    if (!followUpId) return res.status(400).json({ error: 'followUpId required' });

    const requesterId = await getSubscriberId(userEmail);
    if (!requesterId) return res.status(404).json({ error: 'Subscriber not found' });

    const fuRes = await fetch(
      `${SUPABASE_URL}/rest/v1/follow_ups?id=eq.${followUpId}&user_id=eq.${requesterId}&select=id&limit=1`,
      { headers: sbHeaders() }
    );
    const fuRows = await fuRes.json();
    if (!fuRows?.length) return res.status(403).json({ error: 'Only the author can delete their own contribution' });

    await fetch(
      `${SUPABASE_URL}/rest/v1/follow_ups?id=eq.${followUpId}`,
      { method: 'DELETE', headers: sbHeaders() }
    );
    return res.status(200).json({ success: true });
  }

  return res.status(405).json({ error: 'Method not allowed' });
}
