// api/followups.js
// Save and retrieve follow-up queries for a thread — the main Q&A chain
// (R1, R2, R3...), billed, generated by real /api/interpret calls.
//
// ALSO handles Refractions private notes ("My Thoughts") — merged into this
// same file/function rather than a separate api/refractions.js, specifically
// to stay within Vercel Hobby's 12-Serverless-Function limit. Requests for
// notes are distinguished by a ?kind=note query param and routed to
// handleNoteRequest() below; everything else falls through to the original
// follow-up logic. Same behavior either way, just one fewer file deployed.
//
// Contexts the follow-up logic handles:
//   1. Owner (x-user-email) — full access to their own thread
//   2. Share page (x-share-id) — anonymous read/write on a shared thread,
//      unrelated to Trust Circle — this is the original, free, no-account
//      commentary feature and is untouched by anything below
//   3. Trust Circle participant (x-user-email) — an authenticated person who
//      has joined a Trust Circle thread via thread_participants, adding a
//      genuine new interpretive follow-up billed to their own account,
//      exactly as they would in their own thread — no different UI, no
//      different cost, just the same main-view follow-up flow
//
// Visibility note: unlike Refractions notes (refraction_notes), the main
// Q&A chain has NO per-entry private/public split. Once a thread is Trust
// Circle, every follow-up in it is visible to the whole circle by default —
// hiding an actual interpretive answer was confirmed out of scope for this
// table.
//
// Deletion: only the author of a follow-up can ever delete it. Not the
// thread owner, not any other participant, no exceptions.
//
// Muting: purely personal, scoped to (thread, muter, muted). Filtering here
// only ever affects what the MUTER sees — never removes anything for anyone
// else, never notifies the muted person.

import { createHash } from 'node:crypto';
import { verifySupabaseIdentity } from '../lib/server-auth.js';

const SUPABASE_URL              = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY         = process.env.SUPABASE_ANON_KEY;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

function sbHeaders(extra) {
  return {
    'apikey':        SUPABASE_SERVICE_ROLE_KEY,
    'Authorization': `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
    ...extra
  };
}

async function getMutedUserIds(threadId, viewerUserId) {
  if (!viewerUserId) return [];
  const res = await fetch(
    `${SUPABASE_URL}/rest/v1/thread_mutes?thread_id=eq.${threadId}&muter_user_id=eq.${viewerUserId}&select=muted_user_id`,
    { headers: sbHeaders() }
  );
  const rows = await res.json();
  return Array.isArray(rows) ? rows.map(r => r.muted_user_id) : [];
}

// Applies the one viewer-specific filter that applies to the main Q&A
// chain: hide anything from someone this viewer has muted in this thread.
// No per-entry private/public split here — see the file header note.
function filterForViewer(followUps, mutedIds) {
  return followUps.filter(f => !(f.user_id && mutedIds.includes(f.user_id)));
}

function recoveryId(threadId, index, question, response) {
  const hex = createHash('sha256').update(JSON.stringify([threadId, index, question, response])).digest('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(13, 16)}-a${hex.slice(17, 20)}-${hex.slice(20, 32)}`;
}

export { recoveryId };

// ── Claim anonymous session on registration ─────────────────────────────────
// Runs once, immediately after a share recipient completes the "Save This
// Session" free-account flow. Re-keys everything that anon session id
// touched into their new user_id, and adds them as a thread_participant so
// the thread actually surfaces in their sidebar on future visits — without
// that insert, everything below would be correctly re-owned but still
// invisible to them.
//
// Deliberately does NOT touch share_chat_messages. That table has no
// user_id column to re-key at all — Trust Circle "mine" attribution for an
// anonymous sender is (and stays) keyed to the same anon session id, which
// persists in localStorage across registration. Same browser, same
// attribution, no migration needed. A future cross-device claim (via an
// emailed link rather than this same-session flow) would need to solve that
// differently — out of scope here, see the handoff notes on same-session
// as a deliberate, visible limitation rather than a silent one.
//
// Same-session only: anonId is whatever the browser's own prism_anon_id
// currently is. If that's wrong or missing, nothing matches and nothing
// migrates — a no-op, not a misattribution.
async function handleClaimAnonSession(req, res) {
  let body;
  try {
    body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
  } catch {
    return res.status(400).json({ error: 'Invalid JSON' });
  }

  const { anonId, threadId, shareId } = body || {};
  const userId = req.verifiedIdentity?.userId || null;
  if (!anonId || !userId || !threadId) {
    return res.status(400).json({ error: 'anonId, authenticated user, and threadId are required' });
  }
  return res.status(410).json({ error: 'Guest claims are handled by the verified guest-identity boundary' });

  const results = { followUps: false, notes: false, participant: false, fork: null };

  let share = null;
  if (shareId) {
    try {
      const shareRes = await fetch(
        `${SUPABASE_URL}/rest/v1/shares?id=eq.${encodeURIComponent(shareId)}&thread_id=eq.${encodeURIComponent(threadId)}&select=id,permission,status,revoked_at&limit=1`,
        { headers: sbHeaders() }
      );
      const rows = shareRes.ok ? await shareRes.json() : [];
      share = rows?.[0] || null;
    } catch (e) { /* handled by the legacy claim path below */ }
  }

  if (shareId && (!share || share.status !== 'active' || share.revoked_at)) {
    return res.status(410).json({ error: 'This shared connection is no longer active' });
  }

  // A Read Only recipient owns a fork, never membership in the originator's
  // thread. The database function copies the canonical artifact and makes
  // the operation idempotent for this share/account pair.
  if (share && share.permission === 'viewer') {
    const forkRes = await fetch(`${SUPABASE_URL}/rest/v1/rpc/fork_shared_prism_inquiry`, {
      method: 'POST',
      headers: sbHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify({ p_share_id: shareId, p_user_id: userId })
    });
    if (!forkRes.ok) {
      console.error('claim-anon-session: fork failed:', await forkRes.text());
      return res.status(500).json({ error: 'Could not save the shared exchange' });
    }
    const forkRows = await forkRes.json();
    results.fork = forkRows?.[0] || null;

    if (results.fork?.fork_thread_id) {
      await fetch(
        `${SUPABASE_URL}/rest/v1/refraction_notes?anon_session_id=eq.${encodeURIComponent(anonId)}&thread_id=eq.${encodeURIComponent(threadId)}`,
        {
          method: 'PATCH',
          headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'return=minimal' }),
          body: JSON.stringify({
            user_id: userId,
            anon_session_id: null,
            thread_id: results.fork.fork_thread_id
          })
        }
      );
      results.notes = true;
    }
    return res.status(200).json({ success: true, results });
  }

  try {
    const fuRes = await fetch(
      `${SUPABASE_URL}/rest/v1/follow_ups?anon_session_id=eq.${encodeURIComponent(anonId)}&thread_id=eq.${encodeURIComponent(threadId)}`,
      {
        method: 'PATCH',
        headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'return=minimal' }),
        body: JSON.stringify({ user_id: userId, anon_session_id: null })
      }
    );
    results.followUps = fuRes.ok;
    if (!fuRes.ok) console.error('claim-anon-session: follow_ups patch failed:', await fuRes.text());
  } catch (e) { console.error('claim-anon-session: follow_ups patch error:', e); }

  try {
    const notesRes = await fetch(
      `${SUPABASE_URL}/rest/v1/refraction_notes?anon_session_id=eq.${encodeURIComponent(anonId)}&thread_id=eq.${encodeURIComponent(threadId)}`,
      {
        method: 'PATCH',
        headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'return=minimal' }),
        body: JSON.stringify({ user_id: userId, anon_session_id: null })
      }
    );
    results.notes = notesRes.ok;
    if (!notesRes.ok) console.error('claim-anon-session: refraction_notes patch failed:', await notesRes.text());
  } catch (e) { console.error('claim-anon-session: refraction_notes patch error:', e); }

  try {
    const partRes = await fetch(`${SUPABASE_URL}/rest/v1/thread_participants`, {
      method: 'POST',
      headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'resolution=ignore-duplicates,return=minimal' }),
      body: JSON.stringify({ thread_id: threadId, user_id: userId, active: true, last_seen_at: new Date().toISOString() })
    });
    results.participant = partRes.ok;
    if (!partRes.ok) console.error('claim-anon-session: thread_participants insert failed:', await partRes.text());
  } catch (e) { console.error('claim-anon-session: thread_participants insert error:', e); }

  return res.status(200).json({ success: true, results });
}

// ── Join Trust Circle ────────────────────────────────────────────────────────
// Deliberately separate from handleClaimAnonSession above, and deliberately
// NOT automatic. A signed-in visitor opening a shared link can already read
// and comment anonymously via x-share-id, same as anyone else — this is the
// one explicit action that actually makes them a thread_participant: visible
// as a member, able to add others, able to post under their own account
// rather than an anon session. Confirmed-only, on purpose — see the
// consolidation notes on why silent auto-join on link-open was rejected.
async function handleJoinCircle(req, res) {
  const userId = req.verifiedIdentity?.userId || null;
  if (!userId) return res.status(401).json({ error: 'Unauthorized' });

  let body;
  try {
    body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
  } catch {
    return res.status(400).json({ error: 'Invalid JSON' });
  }
  const { threadId } = body || {};
  if (!threadId) return res.status(400).json({ error: 'threadId required' });
  return res.status(410).json({ error: 'Trust Circle access requires an active share credential; save an independent fork to continue' });

  const partRes = await fetch(`${SUPABASE_URL}/rest/v1/thread_participants`, {
    method: 'POST',
    headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'resolution=ignore-duplicates,return=minimal' }),
    body: JSON.stringify({ thread_id: threadId, user_id: userId, active: true, last_seen_at: new Date().toISOString() })
  });

  if (!partRes.ok) {
    const err = await partRes.text();
    console.error('join-circle: thread_participants insert failed:', err);
    return res.status(500).json({ error: 'Could not join' });
  }

  return res.status(200).json({ success: true });
}

// ── Refractions private notes ──────────────────────────────────────────────
// Now backed by its own dedicated table, refraction_notes — no longer
// sharing share_chat_messages with the anonymous social layer at all. That
// was the seam that caused real bugs earlier (the share_id NOT NULL issue);
// a private note has nothing to do with sharing and now lives somewhere
// that reflects that. Still merged into this file rather than its own
// api/refractions.js, purely to stay within Vercel Hobby's 12-function cap.
//
// Author-scoped throughout: a note is only ever visible, editable, or
// deletable by whoever wrote it. quote is optional — a note can exist with
// or without a highlighted passage attached.
async function handleNoteRequest(req, res) {
  const userEmail = req.verifiedIdentity?.email || null;
  const anonId    = req.headers['x-anon-session'] || null;
  if (!userEmail && !anonId) return res.status(401).json({ error: 'Unauthorized' });

  // Resolve to exactly one owner identity — a real account if signed in,
  // otherwise the anonymous session identifier. A note anchored to an
  // anon session today is exactly what the migration step (still to come)
  // will hand over to a real user_id once that session registers.
  const userId = req.verifiedIdentity?.userId || null;

  // Query-string fragment and insert fields, built once, used everywhere
  // below — keeps every branch correct for both identity types without
  // duplicating the same if/else four times.
  const ownerFilter = userId
    ? `user_id=eq.${userId}`
    : `anon_session_id=eq.${encodeURIComponent(anonId)}`;
  const ownerFields = userId
    ? { user_id: userId, anon_session_id: null }
    : { user_id: null, anon_session_id: anonId };

  if (req.method === 'GET') {
    const threadId = req.query?.threadId || null;
    const nodeId    = req.query?.nodeId  || 'root';
    if (!threadId) return res.status(400).json({ error: 'threadId required' });

    const notesRes = await fetch(
      `${SUPABASE_URL}/rest/v1/refraction_notes?thread_id=eq.${encodeURIComponent(threadId)}&node_id=eq.${encodeURIComponent(nodeId)}&${ownerFilter}&order=created_at.asc&select=id,quote,title,content,created_at,edited_at`,
      { headers: sbHeaders() }
    );
    const notes = await notesRes.json();
    return res.status(200).json({ notes: Array.isArray(notes) ? notes : [] });
  }

  if (req.method === 'POST') {
    let body;
    try {
      body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    } catch {
      return res.status(400).json({ error: 'Invalid JSON' });
    }
    const { threadId, nodeId, content, quote, title } = body || {};
    if (!threadId) return res.status(400).json({ error: 'threadId required' });
    if (!quote && !title) return res.status(400).json({ error: 'quote or title required' });

    const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/refraction_notes`, {
      method: 'POST',
      headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'return=representation' }),
      body: JSON.stringify({
        thread_id: threadId,
        node_id:   nodeId || 'root',
        quote:     quote || null,
        title:     title || null,
        content:   content || '',
        ...ownerFields
      })
    });

    if (!insertRes.ok) {
      const err = await insertRes.text();
      console.error('note insert failed:', err);
      return res.status(500).json({ error: 'Failed to save note' });
    }

    const saved = await insertRes.json();
    return res.status(200).json({ success: true, note: saved?.[0] || null });
  }

  if (req.method === 'PATCH') {
    let body;
    try {
      body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    } catch {
      return res.status(400).json({ error: 'Invalid JSON' });
    }
    const { noteId, content, title } = body || {};
    if (!noteId) return res.status(400).json({ error: 'noteId required' });
    if (content === undefined && title === undefined) {
      return res.status(400).json({ error: 'content or title required' });
    }

    const ownRes = await fetch(
      `${SUPABASE_URL}/rest/v1/refraction_notes?id=eq.${noteId}&${ownerFilter}&select=id&limit=1`,
      { headers: sbHeaders() }
    );
    const ownRows = await ownRes.json();
    if (!ownRows?.length) return res.status(403).json({ error: 'Only the author can edit this note' });

    const updates = { edited_at: new Date().toISOString() };
    if (content !== undefined) updates.content = content;
    if (title !== undefined) updates.title = title;

    await fetch(
      `${SUPABASE_URL}/rest/v1/refraction_notes?id=eq.${noteId}`,
      {
        method: 'PATCH',
        headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'return=minimal' }),
        body: JSON.stringify(updates)
      }
    );
    return res.status(200).json({ success: true });
  }

  if (req.method === 'DELETE') {
    const { noteId } = req.body || {};
    if (!noteId) return res.status(400).json({ error: 'noteId required' });

    const ownRes = await fetch(
      `${SUPABASE_URL}/rest/v1/refraction_notes?id=eq.${noteId}&${ownerFilter}&select=id&limit=1`,
      { headers: sbHeaders() }
    );
    const ownRows = await ownRes.json();
    if (!ownRows?.length) return res.status(403).json({ error: 'Only the author can delete this note' });

    await fetch(
      `${SUPABASE_URL}/rest/v1/refraction_notes?id=eq.${noteId}`,
      { method: 'DELETE', headers: sbHeaders() }
    );
    return res.status(200).json({ success: true });
  }

  return res.status(405).json({ error: 'Method not allowed' });
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PATCH, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, x-share-id, x-share-token');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const auth = await verifySupabaseIdentity({
    authorizationHeader: req.headers.authorization,
    supabaseUrl: SUPABASE_URL,
    supabaseAnonKey: SUPABASE_ANON_KEY
  });
  if (auth.provided && !auth.identity) {
    return res.status(auth.unavailable ? 503 : 401).json({ error: auth.unavailable ? 'Identity provider unavailable' : 'Unauthorized' });
  }
  req.verifiedIdentity = auth.identity;

  // Route to the notes branch before anything else — completely separate
  // logic, sharing only the file and the sbHeaders helper
  // to stay within the serverless function count limit.
  if (req.query?.kind === 'note') {
    return handleNoteRequest(req, res);
  }

  if (req.method === 'POST' && req.query?.action === 'claim-anon-session') {
    return handleClaimAnonSession(req, res);
  }

  if (req.method === 'POST' && req.query?.action === 'join-circle') {
    return handleJoinCircle(req, res);
  }

  const userEmail = req.verifiedIdentity?.email || null;
  const authenticatedUserId = req.verifiedIdentity?.userId || null;
  const shareId   = req.headers['x-share-id']   || null;
  const shareToken = req.headers['x-share-token'] || null;

  // ── GET — fetch follow-ups for a thread ──────────────────────────────────
  if (req.method === 'GET') {
    const threadId = req.query?.threadId || null;
    if (!threadId) return res.status(400).json({ error: 'threadId required' });

    // Share page context — untouched, separate from Trust Circle entirely.
    if (shareId && shareToken) {
      const shareRes = await fetch(
        `${SUPABASE_URL}/rest/v1/shares?id=eq.${encodeURIComponent(shareId)}&token=eq.${encodeURIComponent(shareToken)}` +
        `&thread_id=eq.${encodeURIComponent(threadId)}&status=eq.active&revoked_at=is.null&select=id,permission,created_at&limit=1`,
        { headers: sbHeaders() }
      );
      const shares = await shareRes.json();
      if (shares?.length) {
        const share = shares[0];
        const snapshotBoundary = share.permission === 'viewer'
          ? `&created_at=lte.${encodeURIComponent(share.created_at)}`
          : '';
        const fuRes = await fetch(
          `${SUPABASE_URL}/rest/v1/follow_ups?thread_id=eq.${encodeURIComponent(threadId)}${snapshotBoundary}&order=created_at.asc&select=id,query,response,source,created_at,share_id,user_id,display_name`,
          { headers: sbHeaders() }
        );
        const followUps = await fuRes.json();
        return res.status(200).json({ followUps: Array.isArray(followUps) ? followUps : [] });
      }
    }

    if (!userEmail) return res.status(401).json({ error: 'Unauthorized' });

    const viewerUserId = authenticatedUserId;

    const threadRes = await fetch(`${SUPABASE_URL}/rest/v1/threads?id=eq.${threadId}&select=id,user_id&limit=1`, { headers: sbHeaders() });
    const threadRows = await threadRes.json();
    const isOwner = threadRows?.[0]?.user_id === viewerUserId;

    if (!isOwner) {
      return res.status(403).json({ error: 'Not authorized to view this thread' });
    }

    const fuRes = await fetch(
      `${SUPABASE_URL}/rest/v1/follow_ups?thread_id=eq.${encodeURIComponent(threadId)}&order=created_at.asc&select=id,query,response,source,created_at,share_id,user_id,display_name`,
      { headers: sbHeaders() }
    );
    const followUps = await fuRes.json();
    const mutedIds = await getMutedUserIds(threadId, viewerUserId);
    const visible = filterForViewer(Array.isArray(followUps) ? followUps : [], mutedIds);

    return res.status(200).json({ followUps: visible });
  }

  // ── POST — save a follow-up ───────────────────────────────────────────────
  if (req.method === 'POST') {
    let body;
    try {
      body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    } catch {
      return res.status(400).json({ error: 'Invalid JSON' });
    }

    if (body?.action === 'recover_local') {
      const threadId = body.threadId;
      const entries = body.followUps;
      if (!authenticatedUserId || !userEmail) return res.status(401).json({ error: 'Sign in required' });
      if (!/^[0-9a-f-]{36}$/i.test(threadId || '') || !Array.isArray(entries)
        || entries.length < 1 || entries.length > 100) {
        return res.status(400).json({ error: 'Invalid local follow-up history' });
      }
      const normalized = entries.map((item, index) => ({
        index,
        question: typeof item?.question === 'string' ? item.question.trim() : '',
        response: (typeof item?.response === 'string' ? item.response
          : (typeof item?.response?.text === 'string' ? item.response.text : '')).trim(),
      }));
      if (normalized.some(item => !item.question || !item.response
        || item.question.length > 12000 || item.response.length > 16000)) {
        return res.status(400).json({ error: 'Invalid local follow-up entry' });
      }
      const ownerRes = await fetch(
        `${SUPABASE_URL}/rest/v1/threads?id=eq.${encodeURIComponent(threadId)}&user_id=eq.${encodeURIComponent(authenticatedUserId)}&select=id&limit=1`,
        { headers: sbHeaders() }
      );
      const owned = ownerRes.ok ? await ownerRes.json() : [];
      if (!owned?.length) return res.status(403).json({ error: 'Thread ownership required' });

      // Count matching server entries so retrying the same local cache is
      // harmless, including where canonical revisions already exist.
      const [legacyRes, artifactRes] = await Promise.all([
        fetch(`${SUPABASE_URL}/rest/v1/follow_ups?thread_id=eq.${encodeURIComponent(threadId)}&source=eq.owner_local_recovery&select=query,response`, { headers: sbHeaders() }),
        fetch(`${SUPABASE_URL}/rest/v1/interpretation_artifacts?thread_id=eq.${encodeURIComponent(threadId)}&artifact_revision=gt.1&select=artifact`, { headers: sbHeaders() }),
      ]);
      if (!legacyRes.ok || !artifactRes.ok) return res.status(503).json({ error: 'History unavailable; retry later' });
      const existing = [
        ...(await legacyRes.json()).map(row => [row.query, row.response?.text || '']),
        ...(await artifactRes.json()).map(row => [row.artifact?.query, row.artifact?.canonicalResponse]),
      ];
      const counts = new Map();
      for (const pair of existing) {
        const key = JSON.stringify(pair);
        counts.set(key, (counts.get(key) || 0) + 1);
      }
      const missing = normalized.filter(item => {
        const key = JSON.stringify([item.question, item.response]);
        const count = counts.get(key) || 0;
        if (count) { counts.set(key, count - 1); return false; }
        return true;
      });
      if (!missing.length) return res.status(200).json({ synced: true, added: 0 });
      const importedAt = Date.now();
      const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/follow_ups?on_conflict=id`, {
        method: 'POST',
        headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'resolution=ignore-duplicates,return=minimal' }),
        body: JSON.stringify(missing.map(item => ({
          id: recoveryId(threadId, item.index, item.question, item.response),
          thread_id: threadId,
          // Legacy follow_ups.user_id references subscribers.id, while the
          // canonical owner identity is auth.users.id. Ownership was verified
          // above; never put an auth ID into this legacy foreign key.
          user_id: null,
          query: item.question,
          response: { text: item.response },
          created_at: new Date(importedAt + item.index).toISOString(),
          query_cost: 0,
          submitted_in: 'solo',
          source: 'owner_local_recovery',
        }))),
      });
      if (!insertRes.ok) return res.status(503).json({ error: 'Could not sync saved follow-ups' });
      return res.status(200).json({ synced: true, added: missing.length });
    }

    const { threadId, question, response, source, shareId: bodyShareId, anonSessionId } = body || {};
    if (!threadId || !question) return res.status(400).json({ error: 'threadId and question required' });

    const postSource  = source || 'owner';
    const postShareId = bodyShareId || shareId || null;

    if (postSource === 'recipient' && postShareId) {
      if (!shareToken) {
        return res.status(403).json({ error: 'Share credential required' });
      }
      const shareRes = await fetch(
        `${SUPABASE_URL}/rest/v1/shares?id=eq.${encodeURIComponent(postShareId)}&token=eq.${encodeURIComponent(shareToken)}&thread_id=eq.${encodeURIComponent(threadId)}&status=eq.active&revoked_at=is.null&permission=eq.contributor&select=id,recipient_name&limit=1`,
        { headers: sbHeaders() }
      );
      const shares = await shareRes.json();
      if (!shares?.length) {
        return res.status(403).json({ error: 'Share not found, inactive, or does not match thread' });
      }

      const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/follow_ups`, {
        method: 'POST',
        headers: sbHeaders({ 'Content-Type': 'application/json', 'Prefer': 'return=representation' }),
        body: JSON.stringify({
          thread_id:       threadId,
          user_id:         null,
          query:           question,
          response:        typeof response === 'string' ? { text: response } : (response || {}),
          query_cost:      0,
          submitted_in:    'share',
          source:          'recipient',
          share_id:        postShareId,
          anon_session_id: anonSessionId || null,
          display_name:    shares[0].recipient_name || 'Guest'
        })
      });
      if (!insertRes.ok) {
        return res.status(500).json({ error: 'Could not save shared contribution' });
      }
      const inserted = await insertRes.json();
      return res.status(200).json({ success: true, followUp: inserted?.[0] || null });
    }

    if (postSource === 'participant') {
      return res.status(409).json({
        error: 'Trust Circle members may comment, but must fork before asking The Prism a follow-up',
        code: 'TRUST_CIRCLE_FORK_REQUIRED',
      });
    }

    // Canonical completion in /api/interpret owns durable follow-up
    // persistence, lineage, revisioning, and accounting. This endpoint is
    // intentionally read-only for the historical follow_ups collection;
    // retaining an owner dual-write would create a second, non-authoritative
    // persistence record across incompatible identity domains.
    return res.status(410).json({
      error: 'Legacy follow-up writes are retired; canonical artifact persistence is authoritative',
      code: 'LEGACY_FOLLOWUP_WRITE_RETIRED'
    });
  }

  // ── DELETE — remove my own contribution ──────────────────────────────────
  if (req.method === 'DELETE') {
    if (!userEmail) return res.status(401).json({ error: 'Unauthorized' });
    const { followUpId } = req.body || {};
    if (!followUpId) return res.status(400).json({ error: 'followUpId required' });

    const requesterId = authenticatedUserId;

    const fuRes = await fetch(
      `${SUPABASE_URL}/rest/v1/follow_ups?id=eq.${followUpId}&user_id=eq.${requesterId}&select=id&limit=1`,
      { headers: sbHeaders() }
    );
    const fuRows = await fuRes.json();
    if (!fuRows?.length) return res.status(403).json({ error: 'Only the author can delete their own contribution' });

    await fetch(
      `${SUPABASE_URL}/rest/v1/follow_ups?id=eq.${followUpId}`,
      { method: 'DELETE', headers: sbHeaders() }
    );
    return res.status(200).json({ success: true });
  }

  return res.status(405).json({ error: 'Method not allowed' });
}
